import style from "./HomePage.module.css";
// import products from "../../data.js";
import { Outlet, useNavigate } from "react-router-dom";
import { useEffect, useState, useMemo } from "react";
import { db } from "../../configDB/firebase";
import {
  getDocs,
  collection,
  doc,
  query,
  where,
  addDoc,
  updateDoc,
} from "firebase/firestore";

import { toast, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import {
  getInitialProductStateAsync,
  productSelector,
} from "../../redux/reducers/productReducer";
import { useDispatch, useSelector } from "react-redux";
import Footer from "../../components/Footer/Footer";
import Hero from "../../components/Hero/Hero";

function HomePage(props) {
  // const [products, setProducts] = useState([]);
  const { products, loading, error } = useSelector(productSelector); // access store via todoReducer

  const [searchTerm, setSearchTerm] = useState("");
  const [selectedCategories, setSelectedCategories] = useState([]);
  const [maxPrice, setMaxPrice] = useState(99999);
  // const { setCartItems, users, isLoggedIn } = props;
  const { users, isLoggedIn } = props;
  const navigate = useNavigate();
  const dispatch = useDispatch();

  ///derived state pattern
  const filteredProducts = useMemo(() => {
    return products.filter((product) => {
      const matchesSearch = product.title
        .toLowerCase()
        .trim()
        .includes(searchTerm.trim().toLowerCase());

      const matchesPrice = product.price <= maxPrice;

      const matchesCategory =
        selectedCategories.length === 0 ||
        selectedCategories.includes(product.category);

      return matchesSearch && matchesPrice && matchesCategory;
    });
  }, [products, searchTerm, maxPrice, selectedCategories]);

  ///fetch all products from google cloud firestore, mimic componentDidMount lifecycle method
  useEffect(() => {
    // const fetchProducts = async () => {
    //   const querySnapshot = await getDocs(collection(db, "products"));
    //   const productsData = querySnapshot.docs.map((doc) => {
    //     return { ...doc.data(), id: doc.id };
    //   });
    //   // console.log(productsData);
    //   setProducts(productsData);
    // };
    // fetchProducts();

    ///here dispatching getInitialStateAsync action in the productReducer.js file  but outside
    //the Slice function which is a pure funtion (contains actions and reducers autogenerated
    //by toolkit)
    dispatch(getInitialProductStateAsync()); // this becomes action
  }, [dispatch]);

  const showSuccessToast = () =>
    toast.success("🛒 Product added successfully!", {
      position: "top-right",
      autoClose: 2000,
      hideProgressBar: false,
      pauseOnHover: true,
      draggable: true,
    });

  // Add to Cart with Firestore
  async function handleAddToCart(productId) {
    if (!isLoggedIn) {
      navigate("/signin");
      return;
    }

    try {
      const product = products.find((p) => p.id === productId);
      if (!product) {
        console.error("Product not found!");
        return;
      }

      const userId = users?.[0]?.id; //replace with auth.currentUser.uid later
      // console.log("Current userId:", userId);

      if (!userId) {
        toast.error("User not found");
        return;
      }

      const cartRef = collection(db, "cartItems");

      //Query Firestore to check if item already exists for this user
      const q = query(
        cartRef,
        where("userId", "==", userId),
        where("productId", "==", productId)
      );

      const querySnapshot = await getDocs(q);

      if (!querySnapshot.empty) {
        // Item exists → update quantity
        const existingDoc = querySnapshot.docs[0];
        const existingData = existingDoc.data();

        await updateDoc(doc(db, "cartItems", existingDoc.id), {
          quantity: existingData.quantity + 1,
        });

        // Update local state
        // setCartItems((prev) =>
        //   prev.map((item) =>
        //     item.userId === userId && item.productId === productId
        //       ? { ...item, quantity: item.quantity + 1 }
        //       : item
        //   )
        // );

        // ✅ Show success toast
        showSuccessToast();
      } else {
        //Item doesn’t exist → create new doc with auto-ID
        const newCartItem = {
          userId,
          productId: product.id,
          price: product.price,
          quantity: 1,
        };

        const newDocRef = await addDoc(cartRef, newCartItem);
        console.log(newDocRef.id);

        // ✅ Update local state (include Firestore-generated ID for consistency)
        // setCartItems((prev) => [...prev, { ...newCartItem, id: newDocRef.id }]);

        // ✅ Show success toast
        showSuccessToast();
      }
    } catch (err) {
      console.error("Error adding to cart:", err);
      toast.error("🛒 Error adding to cart!");
    }
  }

  if (error) {
    return <h2>{error}</h2>;
  }

  return (
    <>
      <Hero />
      <div className={style.pageLayout}>
        {/* <Outlet context={{ products, setFilteredProducts }} /> */}
        <Outlet
          context={{
            selectedCategories,
            setSelectedCategories,
            maxPrice,
            setMaxPrice,
          }}
        />
        {/* <h1 className="text-4xl font-bold text-purple-600">Tailwind Working</h1> */}
        <div className={style.container}>
          <div className={style.searchContainer}>
            <input
              type="text"
              placeholder="Search By Name"
              className={style.searchInput}
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>

          <div className={style.productContainer}>
            {loading ? (
              <div className={style.loadingContainer}>
                <div className={style.spinner}></div>
                <p>Loading Products...</p>
              </div>
            ) : filteredProducts.length === 0 ? (
              <div className={style.emptyState}>
                <h3>No products found</h3>
                <p>Try adjusting your search or filters.</p>
              </div>
            ) : (
              filteredProducts.map((product) => (
                <div
                  className={style.productCardContainer}
                  key={product.id}
                  id="products-section"
                >
                  <div className={style.productCard}>
                    <img
                      src={product.image}
                      alt={product.title}
                      className={style.productImage}
                    />

                    <div className={style.productName}>{product.title}</div>

                    <div className={style.productPrice}>{product.price}</div>

                    <button
                      className={style.addToCartButton}
                      onClick={() => handleAddToCart(product.id)}
                    >
                      Add to Cart
                    </button>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
        {/* ✅ Toast Container for notifications */}
        <ToastContainer />
      </div>

      {/* Footer  */}
      <Footer />
    </>
  );
}

export default HomePage;

// export default class HomePage extends React.Component {
//   render() {
//     return <div>HomePage</div>;
//   }
// }
